# Launch the default browser when starting the application in development mode
vaadin.launch-browser=true
# To improve the performance during development.
# For more information https://vaadin.com/docs/flow/spring/tutorial-spring-configuration.html#special-configuration-parameters
vaadin.allowed-packages=com.vaadin,org.vaadin,dev.hilla,ai.unified.process.demo.book.library

spring.datasource.url=jdbc:postgresql://localhost:5432/book-library
spring.datasource.username=book-library
spring.datasource.password=book-library

logging.level.org.atmosphere=warn
